pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                 
                 sh '''docker info 

                       docker build -t Dockerfile

                       docker images'''

            }

        }
    }
}
