pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                 
                 sh '''docker info 

                  docker build -t jenkins-demo:${BUILD_NUMBER} . 

docker tag jenkins-demo:${BUILD_NUMBER} jenkins-demo:latest 

docker images'''

            }

        }
    }
}
