pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                 
                 sh '''docker info 

                       docker build -f ${WORKSPACE}/ci-cd-pipeline/Dockerfile -t test:1.1 .

                       docker images'''

            }

        }
    }
}
